interval: 30
quadrants:
  top-left:
    interval: 10
    apps:
      - cpu
      # - app-with-args:
      #     name: snap
      #     args:
      #       - the-way-left.json
      #       - snapshot_files/left
      #       - left
  top-right:
    interval: 300
    apps:
      - temp
      - disk
      # - app-with-args:
      #     name: snap
      #     args:
      #       - the-way-right.json
      #       - snapshot_files/right
      #       - right
  bottom-right:
    interval: 300
    apps:
      - fan
      - net
      # - none
  bottom-left:
    interval: 10
    apps:
      - mem-bat
      # - none
