# Configure apps to be displayed on each quadrant. Optionally cycle though multiple apps
# according to a configured time duration in seconds

# Default duration value, overridden by per-app values if present
duration: 10
quadrants:
  top-left:
  - app:
    name: cpu
    duration: 300
    animate: false
  # Use this pattern for apps with args. Change only the args values
  - app:
    name: snap
    duration: 5
    # If true, scroll entire panel
    animate: true
    scope: panel
    # Snapshot args: file name, file path, panel
    args:
      - zigzag.json
      - snapshot_files/left
      - left
  top-right:
  - app:
    name: temp
    duration: 300
    animate: false
    scope: quadrant
  - app:
    name: snap
    animate: true
    duration: 5
    scope: panel
    args:
      - every-third-row.json
      - snapshot_files/right
      - right
  bottom-right:
  - app:
    name: fan
    duration: 300
    animate: false
  # Keep thhe quadrant blank in this time slot. Used in conjunction with an app
  # in the top quadrant that fills the entire panel, e.g. the snapshot (snap) app
  - app:
    name: none
    duration: 5
    animate: true
  bottom-left:
  - app:
    name: mem-bat
    duration: 300
    animate: false
  - app:
    name: none
    duration: 5
    animate: true
